# Generated by Django 5.1.2 on 2024-10-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0003_alter_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="access_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
