# Generated by Django 5.1.2 on 2024-11-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0004_profile_access_token_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="imdesc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="imported",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playlist",
            name="mood",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="primarycolor",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playlist",
            name="secondarycolor",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
