# Generated by Django 5.1.2 on 2024-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0005_playlist_imdesc_playlist_imported_playlist_mood_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="playlist",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="playlists", to="spotify.genre"
            ),
        ),
    ]
