# Generated by Django 5.1.2 on 2024-12-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0006_genre_playlist_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="cover_img",
            field=models.URLField(blank=True, null=True),
        ),
    ]
